# Generated by Django 4.2.13 on 2026-06-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_name', models.CharField(choices=[('Red Shift', 'Red Shift'), ('Blue Shift', 'Blue Shift'), ('Green Shift', 'Green Shift'), ('Orange Shift', 'Orange Shift')], max_length=30)),
                ('people_amount', models.IntegerField()),
                ('breakdowns', models.CharField(max_length=500)),
                ('assistance_needed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('additiional_comments', models.CharField(max_length=500)),
            ],
        ),
    ]
